Feat. 숫자 야구게임 ! 구현
YUJO42/javascript-baseball-precourse pull request #3
Opened 2023-11-11 06:27 UTC by seongseonko

감사합니다. 재밌었어요!

2023-11-12 04:33 UTC, yujo11 requested changes
안녕하세요 성선님~

재밌으셨다니 다행이네요 ㅎㅎ 코멘트 남긴 내용들 확인해보시고 적용해보시면 좋을거 같습니다!

고생 많으셨어요~~ 👍

2023-11-12 04:33 UTC, yujo11 commented on src/index.js
> +  const empty = new Set(); // 중복을 제거하기 위한 Set
처음 Set을 생성했을 때는 empty인 상태이겠지만 값을 추가하면서 `empty`가 값을 가지게 될텐데요.  다른 적합한 이름을 고민해보셔도 좋을거 같네요 ㅎㅎ

2023-11-12 04:33 UTC, yujo11 commented on src/index.js
> +  let inputValue = e.target.value; // 입력값 변수에 저장
재할당 되지 않는 변수는 `const`를 이용해서 사용해주셔도 좋을거 같네요!

2023-11-12 04:33 UTC, yujo11 commented on src/index.js
> +    isNaN(Number(inputValue)) // 입력값이 숫자로 변환이 안될시 실행
`isNaN`과 `Number.isNaN`이 있는데 두개 메서드는 어떻게 다를까요? 차이에 대해 찾아보셔도 좋을거 같습니다 ㅎㅎ

2023-11-12 04:33 UTC, yujo11 commented on src/index.js
> +input.addEventListener("change", answer); // input 값의 change 이벤트 발생
input의 값이 바뀔 때마다 이벤트가 발생할텐데 유저가 button을 눌렀을 때나 Enter 키를 입력했을 때만 이벤트가 발생하도록 해도 될거 같아요 ㅎㅎ

`keyup`, `click` 이벤트에 대해서 찾아보셔도 좋을거 같습니다

2023-11-12 04:33 UTC, yujo11 commented on src/index.js
> +  let strikeCount = threeNumber.filter((el, i) => el === inputArray[i]).length;
오 메서드를 잘 활용하셨군요 ㅎㅎ 👍 👍 👍 💯 💯

2023-11-13 11:57 UTC, seongseonko commented
감사합니다 되도록 수정해봤습니다!

2023-11-14 14:34 UTC, yujo11 approved these changes
고생 많으셨습니다 성선님 미션이 의미있는 경험이었으면 좋겠네요 ㅎㅎ

2023-11-14 14:34 UTC, yujo11 commented on src/index.js
> +  if (e.type === "click" || (e.type === "keyup" && e.key === "Enter")) {
지금은 `click`과 `keyup`이벤트로 잡고 있는데 요소를 폼으로 감싸고 `submit` 이벤트를 사용해보셔도 좋을거 같네요

```js
<form>
      <input type="text" id="user-input" />
      <button id="submit">확인</button>
</form>
```

2023-11-14 14:34 UTC, yujo11 commented on src/index.js
> +function answer(e) {
하나의 함수에서 굉장히 많은 일을 하고 있는데 다음에는 함수를 좀 더 작게 나눠보셔도 좋을거 같아요~

2023-11-14 14:34 UTC, closed without merging