황채연
YUJO42/javascript-baseball-precourse pull request #4
Opened 2023-11-11 07:31 UTC by Chyyni

- 일단 구현은 해봤습니다.
- 생성자 함수 또는 클래스를 사용해서 만들고 싶은데, 어떻게 해야 할 지 방법이 떠오르지 않습니다.

2023-11-12 05:02 UTC, yujo11 requested changes
안녕하세요 채연님~

전체적으로 함수를 잘 분리하고 깔끔하게 코드를 작성해주셨네요 👍 👍 👍  간단한 코멘트들 남겼으니 확인 부탁드립니다 ㅎㅎ

>생성자 함수 또는 클래스를 사용해서 만들고 싶은데

이 부분은 용준님이 클래스 활용하신 부분이 있어서 용준님 PR보고 힌트를 얻어가셔도 좋을거 같네요!

고생 많으셨습니다~~ 👍

2023-11-12 05:02 UTC, yujo11 commented on src/index.js
> +app.addEventListener('submit', baseballGame);
오 submit event를 활용해주셨군요 👍 👍 👍

2023-11-12 05:02 UTC, yujo11 commented on src/index.js
> +  });
`location.reload()`도 좋은 방법이지만 `reload`가 될 때 화면이 깜박 거릴텐데요. 다른 방법은 없을까요?ㅎㅎ

2023-11-12 05:02 UTC, yujo11 commented on src/index.js
> +'use strict';
👍 👍 👍

2023-11-12 05:02 UTC, yujo11 commented on src/index.js
> +  let set = new Set();
`set`이 const로 선언되면 아래 로직들이 동작하지 않을까요?

2023-11-12 05:02 UTC, yujo11 commented on src/index.js
> +  let set = new Set();
JavaScript의 Primitive Type과 Object Type에 대해서 찾아보셔도 좋을거 같습니다 ㅎㅎ

2023-11-12 05:02 UTC, yujo11 commented on src/index.js
> +  return computerNumbersArray;
축약이 가능한 부분에서는 적절히 축약해서 표현해주시면 가독성이 좋아질거 같네요!

```suggestion
  return [...set];
```

2023-11-12 05:02 UTC, yujo11 commented on src/check_user_num.js
> +  const userEnterNumbers = userInput.value;
Event 객체는 생각보다 많은 값들을 가지고 있는데요.

DOM에서 파싱해오는 대신, Submit Event 객체에서 값을 꺼내어 사용하는 방법을 찾아보셔도 좋을거 같습니다 ㅎㅎ

2023-11-12 05:02 UTC, yujo11 commented on src/check_user_num.js
> +    return userNumbers;
이런 부분도 축약해서 사용해도 될거 같네요 ㅎㅎ
```suggestion
    return [...String(userEnterNumbers)];
```

2023-11-13 08:40 UTC, Chyyni commented on src/index.js
> +  let set = new Set();
단순히 변하는 값이니 let으로 선언했는데, set은 원시 타입이 아니니 const로 선언해도 문제없겠군요.. 배운 것을 적용하지 못했어요ㅎ

2023-11-13 08:42 UTC, Chyyni commented on src/check_user_num.js
> +  const userEnterNumbers = userInput.value;
console.log(e)를 해보니까 이벤트 객체 내에서 값에 접근할 수 있는 방법이 여러가지가 있을 수 있던데, 어떤 방법이든 상관없을까요? 일단 코드를 봤을 때 가장 직관적인 부분이 e.target.elements["user-input"]인 것 같아 이걸 택해서 수정해봤습니다.

2023-11-13 08:44 UTC, Chyyni commented on src/index.js
> +  });
코드가 간결한 것 같아 reload()를 선택했었는데, 화면이 깜박거리는 문제까지 생각하지 못했어요ㅎ (사실 어떻게 해야 초기화를 할 수 있을까 잘 생각해내지 못해서,,) 다른 분들 코드 참고하여 수정해봤습니다.ㅎ

2023-11-13 08:44 UTC, Chyyni commented on src/index.js
> +  return computerNumbersArray;
네 ! ㅎㅎ

2023-11-14 14:39 UTC, yujo11 commented on src/check_user_num.js
> +  const userEnterNumbers = userInput.value;
네네 직관적인 방법을 잘 찾아서 수행해주셨네요 👍 👍 👍

2023-11-14 14:39 UTC, yujo11 commented on src/index.js
> +  let set = new Set();
이렇게 하나씩 적용해나가는 방법을 배워가심 될거 같습니다 ㅎㅎ 👍 👍 👍

2023-11-14 15:04 UTC, yujo11 approved these changes
안녕하세요 채연님~ 리뷰 꼼꼼하게 잘 반영해주셨네요 👍 

채널에 올린 다음 미션(레이싱카 게임)도 진행해보시면 좋을거 같습니다!

2023-11-14 15:04 UTC, yujo11 commented on src/check_user_num.js
> +    return [...str];
👍 👍

2023-11-14 15:04 UTC, yujo11 commented on src/index.js
> +  return [...set];
👍 👍

2023-11-14 15:04 UTC, yujo11 commented on src/check_user_num.js
> +  const userEnterNumbers = e.target.elements['user-input'].value;
👍 👍

2023-11-14 15:04 UTC, yujo11 commented on src/index.js
> +let computerNumberArray = createComputerNumbers();
어렵다고 하셨는데 잘 수행해주셨군요 ㅎㅎ 👍 👍 👍

2023-11-14 15:04 UTC, closed without merging