김광현 숫자야구
YUJO42/javascript-baseball-precourse pull request #7
Opened 2023-11-25 09:34 UTC by SeanKim-416

포크 뜨고 브랜치를 파서 개발했는데 푸시 할라니까 뭔가 에러가 뜨더라구요
그래서 main으로 작업 내용을 옮기느라 커밋이 싹 날라갔습니다...

요구사항을 지켜가면서(indent는 최대 2까지 등) 완성하려고 노력했습니다!
자바스크립트에 대해서 배울 점이 아직 많다는 생각이 드네요 ㅎㅎ

가능하면 직관적인 함수/변수 네이밍을 하려고 시도해봤고,
한 함수에서는 최대한 한 동작만 하도록 노력해봤는데, 잘 된 것인지는 모르겠네요.
이상한 코드뭉치가 된 것 같기도 하고 ㅎ

리뷰 해주시면 읽어보면서, 어떤 점이 부족하고, 더 공부해야 할 지 고민하겠습니다. 감사합니다!
<hr>

![스크린샷 2023-11-25 오후 6 31 09](https://github.com/yujo11/javascript-baseball-precourse/assets/56223156/21ea25c8-15f2-42dd-920a-5eedcd6ffa4a)

![스크린샷 2023-11-25 오후 6 31 51](https://github.com/yujo11/javascript-baseball-precourse/assets/56223156/3888fb35-08cf-4e11-9919-ff763d89ccfd)

![스크린샷 2023-11-25 오후 6 32 03](https://github.com/yujo11/javascript-baseball-precourse/assets/56223156/99fcf314-b31e-47db-b757-168843f68cec)

![스크린샷 2023-11-25 오후 6 32 28](https://github.com/yujo11/javascript-baseball-precourse/assets/56223156/39e82955-1347-4f57-bd76-ff85ae9b84ea)

https://github.com/yujo11/javascript-baseball-precourse/assets/56223156/673c1271-834d-41c4-971a-e9447d9703c6

2023-11-29 16:42 UTC, yujo11 requested changes
안녕하세요 광현님 고생 많으셨습니다~ 

간단한 내용들 코멘트로 남겼는데 확인하고 반영해보시면 좋겠네요~

2023-11-29 16:42 UTC, yujo11 commented on src/createComputerNum.js
> +  let computerNum = '';
`let`을 제거해보시면 좋을거 같아요 ㅎㅎ

2023-11-29 16:42 UTC, yujo11 commented on src/index.js
> +const numArray = [null, null];
변수데이터를 단순히 Array에 담아서 관리하게 되면 코드를 볼 때 0번째, 1번째 인덱스에 어떤 값이 들어있고, 어떻게 사용하는지 알기 어려운데요.

차라리 아래와 같이 객체를 사용해보는건 어떨까요? (예시이니 참고만 해주세요~)

```suggestion
// 게임을 진행할 변수 데이터
const gameInfo = {
   computerNum: null,
   userNum: null
}
```

2023-11-29 16:42 UTC, yujo11 commented on src/index.js
> +  numArray[0] = createComputerNum();
위에 언급한 것과 같이 인덱스를 바로 사용하게 되면 코드를 보는 사람으로 하여금 충분한 정보를 전달하기 어렵습니다.

`numArray[0]`이라는 코드로 알 수 있는건 numArray의 0번째 인덱스라는 정보 뿐인데 왜 `createComputerNum()`을 0번째 인덱스에 넣는지, 이후 어떻게 쓰이는지 예측하기 힘들기 때문에 다른 방법을 고민하시거나 가독성을 높일 방법을 고민해보셨으면 좋겠네요~

2023-11-29 16:42 UTC, yujo11 commented on src/utils.js
> +  }
깔끔하게 구현하셨군요 👍

2023-11-29 16:42 UTC, yujo11 commented on src/utils.js
> +  return strike === 3 ? true : false;
`3`과 같은 매직 넘버도 의미를 전달하기 어렵기 때문에 상수화 해보시는걸 추천 드립니다~

2023-11-29 23:44 UTC, SeanKim-416 commented on src/createComputerNum.js
> +  let computerNum = '';
let을 사용하는 것 외에도 문자열을 합치는 방법이 여럿 있으니까 찾아보고 반영해보겠습니다!

2023-11-29 23:46 UTC, SeanKim-416 commented on src/index.js
> +  numArray[0] = createComputerNum();
이런 면에서는 확실히 위에서 말씀해주신 객체를 사용하는 것이 좀더 가독성 면에서 좋은 방법이 될 것 같다는 생각이 들었습니다!
반영하겠습니다!

2023-11-29 23:50 UTC, SeanKim-416 commented on src/utils.js
> +  }
'코드 depth를 최대 2까지 작성하라'라는 요구사항이 있어서 맞춰보려고 노력했던 부분이네요!
볼과 스트라이크를 요구사항에 부합하면서 분기를 어떻게 나누어야 할 지에 대해 고민했던 기억이 있습니다.
좋게 봐주셔서 감사합니다!

2023-11-29 23:53 UTC, SeanKim-416 commented on src/utils.js
> +  return strike === 3 ? true : false;
매직넘버의 의도 파악 문제에 대해서는 머리로는 알고 있는데, 자꾸 그냥 작성하는게 습관이 되네요.
앞으로 고쳐봐야겠습니다!

2023-11-30 14:49 UTC, yujo11 approved these changes
안녕하세요 광현님 빠르게 리뷰까지 반영하셨군요 👍 

소소한 코멘트 남겼으니 확인 부탁드립니다~ 고생 많으셨어요 👍 👍

2023-11-30 14:49 UTC, yujo11 commented on src/index.js
> +};
👍 👍

2023-11-30 14:49 UTC, yujo11 commented on src/utils.js
> +  return strike === STRIKE_COUNT_TO_WIN ? true : false;
상수화 좋네요~ 👍

2023-11-30 14:49 UTC, yujo11 commented on src/utils.js
> +  return strike === STRIKE_COUNT_TO_WIN ? true : false;
boolean 값을 반환하기 때문에 아래처럼만 작성해줘도 좋을거 같아요~

```
return strike === STRIKE_COUNT_TO_WIN
```

2023-11-30 14:49 UTC, closed without merging